// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb144HspzMoL9VNQn3aQJYiBamyEsAqq4',
    appId: '1:345328001724:web:7e503a48dbe44c3efca6b9',
    messagingSenderId: '345328001724',
    projectId: 'flutter-auth-4b5cd',
    authDomain: 'flutter-auth-4b5cd.firebaseapp.com',
    storageBucket: 'flutter-auth-4b5cd.firebasestorage.app',
    measurementId: 'G-YZBPPHMKMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUDfxB1AEmkonK-gjFlLt6Vm_I8gzOyzY',
    appId: '1:345328001724:android:e120fd549a2bf572fca6b9',
    messagingSenderId: '345328001724',
    projectId: 'flutter-auth-4b5cd',
    storageBucket: 'flutter-auth-4b5cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxuE-LGdNPlEezd1TieKrW5PY7qyv7n6g',
    appId: '1:345328001724:ios:d84c51fa0b8256a0fca6b9',
    messagingSenderId: '345328001724',
    projectId: 'flutter-auth-4b5cd',
    storageBucket: 'flutter-auth-4b5cd.firebasestorage.app',
    androidClientId: '345328001724-uk2clk61fhg2m4od1vkqvm84m230rh0c.apps.googleusercontent.com',
    iosClientId: '345328001724-sul37lps4eqkk8c5r2slmkot8lp4hb9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendFlutterProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxuE-LGdNPlEezd1TieKrW5PY7qyv7n6g',
    appId: '1:345328001724:ios:d84c51fa0b8256a0fca6b9',
    messagingSenderId: '345328001724',
    projectId: 'flutter-auth-4b5cd',
    storageBucket: 'flutter-auth-4b5cd.firebasestorage.app',
    androidClientId: '345328001724-uk2clk61fhg2m4od1vkqvm84m230rh0c.apps.googleusercontent.com',
    iosClientId: '345328001724-sul37lps4eqkk8c5r2slmkot8lp4hb9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendFlutterProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb144HspzMoL9VNQn3aQJYiBamyEsAqq4',
    appId: '1:345328001724:web:9bd440780a8a6631fca6b9',
    messagingSenderId: '345328001724',
    projectId: 'flutter-auth-4b5cd',
    authDomain: 'flutter-auth-4b5cd.firebaseapp.com',
    storageBucket: 'flutter-auth-4b5cd.firebasestorage.app',
    measurementId: 'G-9JS8NN6ZGZ',
  );
}
